name: SOOS DAST GitHub Actions
on: [push]
jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           log_level: DEBUG
           project_name: "dast-githubActions-09"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://brokencrystals.com/"
           auth_form_type: ""
