name: SOOS DAST GitHub Actions
on: [push]
jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "dast-githubActions-23"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "apiscan"
           api_scan_format: "soap"
           target_url: "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
           verbose: "true"
           debug: "true"
