name: SOOS DAST GitHub Actions
on: [push]
jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "dast-githubActions-11"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://demoqa.com/profile"
           auth_username: ${{ secrets.SOOS_DAST_AUTH_USERNAME }}
           auth_password: "invalidPassword"
           auth_login_url: "https://demoqa.com/login"
           auth_verification_url: "https://demoqa.com/Account/v1/User/fbe86d3e-3cd0-4d0c-a13c-d1b19f08644d" #"https://demoqa.com/Account/v1/User/52d9d238-fc85-4f1e-9ce2-50a65397ed29"
           on_failure: "continue_on_failure"
