name: SOOS DAST GitHub Actions
on: [push]
jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@553b54e3cb7de72b3b9dbaba23a4dd747f56253e
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "GitHub Actions - DAST checkoutDir"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://brokencrystals.com/"
           log_level: DEBUG
           image_tag: alpha
           output_format: SARIF
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
