name: SOOS DAST GitHub Actions
on: [push]
jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@54392b5d04181667bc4a7113468704167999704b
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "GitHub Actions - DAST verbose"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://brokencrystals.com/"
           scan_mode: "baseline"
           image_tag: alpha
           verbose: true
           log_level: DEBUG
